name: MC Server
on: push
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Start Server
      run: |
        java -Xmx2048MB -Xms1024MB -jar "server.jar"

    - name: Setup Deploy Private Key
      env:
        WORLD_DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_SECRET_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$WORLD_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Setup Git Infomation
      run: | 
        git config --global user.name "code004Accepted"
        git config --global user.email "code004@qq.com"
        git config --global core.quotepath false

    - name: Save World
      run: |
        git commit -m "World Commit"
        git push -u origin master